# Generated by Django 3.2.12 on 2023-03-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkfarm_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todaysdata',
            name='tod_amt',
            field=models.IntegerField(default=0),
        ),
    ]
