# Generated by Django 3.2.12 on 2023-02-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkfarm_backend_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodaysData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fat', models.DecimalField(decimal_places=2, max_digits=5)),
                ('snf', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('lit', models.DecimalField(decimal_places=2, max_digits=5)),
            ],
        ),
    ]
