# Generated by Django 3.2.12 on 2023-03-16 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkfarm_backend_app', '0002_todaysdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='types',
            field=models.CharField(choices=[('cow', 'cow'), ('buffalo', 'buffalo')], default=0, max_length=100),
        ),
    ]
