# Generated by Django 3.2.12 on 2023-03-16 10:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('milkfarm_backend_app', '0003_member_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todaysdata',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milkfarm_backend_app.member'),
        ),
    ]
