# Generated by Django 3.2.12 on 2023-03-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milkfarm_backend_app', '0004_auto_20230325_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='lit',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='payment',
            name='myname',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
